DATA ORDERS;
 INFILE "C:\Users\user\Desktop\SAS\DATA\MyRawData\Coffee.dat";
 INPUT COFFEE $ WINDOW $ @@;
PROC FREQ DATA = ORDERS;
 TABLES WINDOW WINDOW*COFFEE /LIST MISSPRINT;
RUN;


DATA ORDERS_1;
 INFILE "C:\Users\user\Desktop\SAS\DATA\MyRawData\Coffee.dat";
 INPUT COFFEE $ WINDOW $ @@;
PROC FORMAT;
 VALUE $COFFEEFMT  "esp" = "ESPRESSO"
 "kon" = "KONA"
 "Kon" = "KONA"
 "cap" = "CAPPUCCINO"
 "ice" = "ICED COFFEE"
 OTHER = "MISSING";
 VALUE $WINDOWFMT "d" = "DRIVE-UP"
 "w" = "WALKED-IN";
RUN;
PROC FREQ DATA = ORDERS_1;
 FORMAT WINDOW $WINDOWFMT.;
 FORMAT COFFEE $COFFEEFMT.;
 TABLES WINDOW*COFFEE /NOROW NOCOL NOPERCENT MISSING;
 LABEL COFFEE = "(TEST)";
RUN;


DATA BOATS;
 INFILE "C:\Users\user\Desktop\SAS\DATA\MyRawData\Boats.dat";
 INPUT NAME $ 1-12 PORT $ 14-20 LOCO $ 22-26 TYPE $ 28-30 PRICE 32-37 LENGTH 39-41;
RUN;
PROC TABULATE DATA = BOATS;
 CLASS PORT LOCO TYPE;
 TABLE PORT, LOCO, TYPE;
 TITLE "NUMBER OF BOATS";
RUN;

DATA BOATS;
 INFILE "C:\Users\user\Desktop\SAS\DATA\MyRawData\Boats.dat";
 INPUT NAME $ 1-12 PORT $ 14-20 LOCO $ 22-26 TYPE $ 28-30 PRICE 32-37 LENGTH 39-41;
RUN;
PROC TABULATE DATA = BOATS FORMAT = DOLLAR9.2;
 CLASS LOCO;
 VAR PRICE;
 TABLE LOCO ALL, MEAN*PRICE*(TYPE ALL) /BOX="FULL DAY EXE" MISSTEXT = "NONE";
 TITLE;
RUN;

DATA BOATS;
 INFILE "C:\Users\user\Desktop\SAS\DATA\MyRawData\Boats.dat";
 INPUT NAME $ 1-12 PORT $ 14-20 LOCO $ 22-26 TYPE $ 28-30 PRICE 32-37 LENGTH 39-41;
RUN;
PROC FORMAT;
 VALUE $TYPE "cat" = "catamaran" "sch" = "schooner" "yac" = "yacht";
PROC TABULATE DATA = BOATS FORMAT = DOLLAR9.2;
 CLASS LOCO TYPE;
 VAR PRICE;
 FORMAT TYPE $TYPE;
 TABLE LOCO="" ALL , MEAN=""*PRICE="MEAN PRICE"*(TYPE="" ALL) /BOX = "FULL DAY" MISSTEXT="NONE";
RUN;
