/*CH1*/
DATA DISTANCE  ;
        MILES = 26.22;
        KILOMETER = 1.61*MILES;
RUN;

PROC PRINT DATA = DISTANCE;
RUN ;

PROC CONTENTS DATA = DISTANCE;
RUN;

LIBNAME TEST "C:\Users\user\Desktop\SAS";
RUN ;

PROC OPTION;
RUN;

/*CH2*/
PROC IMPORT OUT= WORK.ABC
            DATAFILE= "C:\Users\user\Desktop\SAS\DATA\MyRawData\Bands2.csv"
            DBMS=CSV REPLACE;
     GETNAMES=YES;
     DATAROW=2;
RUN;

        /*READ INTERNAL DATA*/
DATA USPRESIDENTS;
 INPUT PRESIDENT $ PARTY $ NUMBER ;
 DATALINES ;
        ADAM F 2
        LINCON R 16
        GRANT R 18
        KENNEDY D 35;
 RUN;

DATA TOADS ;
INFILE "C:\Users\user\Desktop\SAS\DATA\MyRawData\ToadJump.dat";
INPUT TOADNAME $ WEIGHT JUMP1 JUMP2 JUMP3;
RUN ;
PROC PRINT DATA = TOADS;
TITLE "SAS DATA SET TOADS";
RUN ;
