DATA CANCERESULTS;
 INFILE 'C:\Users\user\Desktop\SAS\DATA\MyRawData\Canoes.dat';
 INPUT @'School:' SCHOOL $ @'Time:' RACETIME :STIMER8.;
 RUN ;

PROC PRINT DATA = CANCERESULTS;
 TITLE "LOL" ;
 RUN ;


DATA WWWTEST;
 INPUT AGE SITE :$41. HITS COMMA7.;
 DATALINES ;
12 http://www.sites1.org/default.html 123,456
130 http://www.sites2.org/default.html 97,654
254 http://www.sites3.org/default.html 987,654
;
RUN;
PROC PRINT DATA = WWWTEST;
 TITLE "TEST" ;
 RUN;


DATA TEMPERATURE;
 INFILE 'C:\Users\user\Desktop\SAS\DATA\MyRawData\Temperature.dat';
 INPUT CITY $ STAT $
  / NORMALHIGH NORMALLOW
  #3 RECORDHIGH RECORDLOW;
RUN ;

PROC PRINT DATA = TEMPERATURE;
 TITLE "TEST" ;
 RUN ;


DATA FREEWAYS ;
 INFILE 'C:\Users\user\Desktop\SAS\DATA\MyRawData\Traffic.dat' ;
 INPUT TYPE $ @;
 IF TYPE = 'surface' THEN DELETE;
 INPUT NAME $9-38 AMTTRAFFIC PMTTRAFFIC;
RUN ;

PROC PRINT DATA = FREEWAYS ;
 TITLE "TEST" ;
 RUN ;

DATA GENDER;
 INPUT GENDER $1. @;
 IF GENDER = 'M' THEN DELETE;
 INPUT  @3 AGE 2.  @5 HEIGHT 2. ;
 DATALINES;
    M 2368
    F 4462
 ;
RUN;

PROC PRINT DATA = GENDER;
 TITLE "TEST"
 RUN ;

DATA CLASS102;
 INFILE 'C:\Users\user\Desktop\SAS\DATA\MyRawData\ALLScores.dat'MISSOVER;
 INPUT NAME $ TEST1 TEST2 TEST3 TEST4 TEST5 ;
RUN;

PROC PRINT DATA = CLASS102;
RUN ;

DATA PUMPKIN;
 INFILE 'C:\Users\user\Desktop\SAS\DATA\MyRawData\Pumpkin.dat';
 INPUT NAME $16.  AGE @;
 IF AGE > 10 THEN DELETE ;
 INPUT TYPE DATE MMDDYY5. SCORE1 @ ;
 IF SCORE1 >= 8 THEN GRADE1 = "A" ;
 INPUT (SCORE2 SCORE3 SCORE4 SCORE5)(2.1) ;
RUN ;
PROC PRINT DATA = PUMPKIN;
RUN ;
DATA CANCERESULTS;
 INFILE 'C:\Users\user\Desktop\SAS\DATA\MyRawData\Canoes.dat';
 INPUT @'School:' SCHOOL $ @'Time:' RACETIME :STIMER8.;
 RUN ;

PROC PRINT DATA = CANCERESULTS;
 TITLE "LOL" ;
 RUN ;


DATA WWWTEST;
 INPUT AGE SITE :$41. HITS COMMA7.;
 DATALINES ;
12 http://www.sites1.org/default.html 123,456
130 http://www.sites2.org/default.html 97,654
254 http://www.sites3.org/default.html 987,654
;
RUN;
PROC PRINT DATA = WWWTEST;
 TITLE "TEST" ;
 RUN;


DATA TEMPERATURE;
 INFILE 'C:\Users\user\Desktop\SAS\DATA\MyRawData\Temperature.dat';
 INPUT CITY $ STAT $
  / NORMALHIGH NORMALLOW
  #3 RECORDHIGH RECORDLOW;
RUN ;

PROC PRINT DATA = TEMPERATURE;
 TITLE "TEST" ;
 RUN ;


DATA FREEWAYS ;
 INFILE 'C:\Users\user\Desktop\SAS\DATA\MyRawData\Traffic.dat' ;
 INPUT TYPE $ @;
 IF TYPE = 'surface' THEN DELETE;
 INPUT NAME $9-38 AMTTRAFFIC PMTTRAFFIC;
RUN ;

PROC PRINT DATA = FREEWAYS ;
 TITLE "TEST" ;
 RUN ;

DATA GENDER;
 INPUT GENDER $1. @;
 IF GENDER = 'M' THEN DELETE;
 INPUT  @3 AGE 2.  @5 HEIGHT 2. ;
 DATALINES;
    M 2368
    F 4462
 ;
RUN;

PROC PRINT DATA = GENDER;
 TITLE "TEST"
 RUN ;

DATA CLASS102;
 INFILE 'C:\Users\user\Desktop\SAS\DATA\MyRawData\ALLScores.dat'MISSOVER;
 INPUT NAME $ TEST1 TEST2 TEST3 TEST4 TEST5 ;
RUN;

PROC PRINT DATA = CLASS102;
RUN ;

DATA PUMPKIN;
 INFILE 'C:\Users\user\Desktop\SAS\DATA\MyRawData\Pumpkin.dat';
 INPUT NAME $16.  AGE @;
 IF AGE > 10 THEN DELETE ;
 INPUT TYPE $1.+1 DATE MMDDYY10. SCORE1 @ ;
 IF SCORE1 >= 8 THEN GRADE1 = "A" ;
 INPUT (SCORE2 SCORE3 SCORE4 SCORE5)(3.1+1) ;
RUN ;
PROC PRINT DATA = PUMPKIN;
RUN;
DATA CANCERESULTS;
 INFILE 'C:\Users\user\Desktop\SAS\DATA\MyRawData\Canoes.dat';
 INPUT @'School:' SCHOOL $ @'Time:' RACETIME :STIMER8.;
 RUN ;

PROC PRINT DATA = CANCERESULTS;
 TITLE "LOL" ;
 RUN ;


DATA WWWTEST;
 INPUT AGE SITE :$41. HITS COMMA7.;
 DATALINES ;
12 http://www.sites1.org/default.html 123,456
130 http://www.sites2.org/default.html 97,654
254 http://www.sites3.org/default.html 987,654
;
RUN;
PROC PRINT DATA = WWWTEST;
 TITLE "TEST" ;
 RUN;


DATA TEMPERATURE;
 INFILE 'C:\Users\user\Desktop\SAS\DATA\MyRawData\Temperature.dat';
 INPUT CITY $ STAT $
  / NORMALHIGH NORMALLOW
  #3 RECORDHIGH RECORDLOW;
RUN ;

PROC PRINT DATA = TEMPERATURE;
 TITLE "TEST" ;
 RUN ;


DATA FREEWAYS ;
 INFILE 'C:\Users\user\Desktop\SAS\DATA\MyRawData\Traffic.dat' ;
 INPUT TYPE $ @;
 IF TYPE = 'surface' THEN DELETE;
 INPUT NAME $9-38 AMTTRAFFIC PMTTRAFFIC;
RUN ;

PROC PRINT DATA = FREEWAYS ;
 TITLE "TEST" ;
 RUN ;

DATA GENDER;
 INPUT GENDER $1. @;
 IF GENDER = 'M' THEN DELETE;
 INPUT  @3 AGE 2.  @5 HEIGHT 2. ;
 DATALINES;
    M 2368
    F 4462
 ;
RUN;

PROC PRINT DATA = GENDER;
 TITLE "TEST"
 RUN ;

DATA CLASS102;
 INFILE 'C:\Users\user\Desktop\SAS\DATA\MyRawData\ALLScores.dat'MISSOVER;
 INPUT NAME $ TEST1 TEST2 TEST3 TEST4 TEST5 ;
RUN;

PROC PRINT DATA = CLASS102;
RUN ;

DATA PUMPKIN;
 INFILE 'C:\Users\user\Desktop\SAS\DATA\MyRawData\Pumpkin.dat';
 INPUT NAME $16.  AGE @;
 IF AGE > 10 THEN DELETE ;
 INPUT TYPE $1.+1 DATE MMDDYY10.+1 (SCORE1 SCORE2 SCORE3 SCORE4 SCORE5)(3.1+1) @ ;
 IF SCORE1 >= 8 THEN GRADE1 = "A" ;
RUN ;
PROC PRINT DATA = PUMPKIN;
RUN;
