DATA HOMEGARDEN;
  INFILE "C:\Users\user\Desktop\SAS\DATA\MyRawData\Garden.dat";
  INPUT NAME $ 1-7 TOMATO ZUCCHINI PEAS GRAPES;
  ZONE = 14;
  TYPE = 'HOME';
  ZUCCHINI = ZUCCHINI*10;
  TOTAL = TOMATO + ZUCCHINI + PEAS + GRAPES;
RUN;

PROC PRINT DATA = HOMEGARDEN;
 TITLE "HOMEGARDEN";
RUN ;

DATA SCORE;
 INFILE "C:\Users\user\Desktop\SAS\DATA\MyRawData\Pumpkin.dat";
 INPUT NAME $ 16. AGE 3.+1 TYPE $ 1.+1 DATE MMDDYY10. (SCR1 SCR2 SCR3 SCR4 SCR5)(4.1);
 AVGSCORE = MEAN(OF SCR1-SCR5);
 DAYENTER = DAY(DATE);
 TYPE = UPCASE(TYPE);
RUN;

PROC PRINT DATA = SCORE;
 TITLE "SCORE";
RUN;


DATA _NULL_;
 INPUT NAMES $ 1-10 SEX $ 12 AGE 15-16;
 PUT NAMES SEX AGE;
 DATALINES;
 JOSECH     M  13
 MICHAEL    M  14
 SUE ELLAN  F  11
;
RUN;

DATA TEST_CAT;
A = ' A ';
B = ' B ';
C = ' C ';
CAT_EXAMPLE = CAT(A,B,C);
CATT_EXAMPLE = CATT(A,B,C);
TRIM_EXAMPLE = CAT(TRIM(A),TRIM(B),TRIM(C));
CATS_EXAMPLE = CATS(A,B,C);
TRIMLEFT_EXAMPLE = CAT(TRIM(LEFT(A)),TRIM(LEFT(B)),TRIM(LEFT(C)));
CATX_EXAMPLE = CATX(',',A,B,C);
PUT CAT_EXAMPLE $CHAR;
PUT CATT_EXAMPLE $CHAR;
PUT TRIM_EXAMPLE $CHAR;
PUT CATS_EXAMPLE $CHAR;
PUT TRIMLEFT_EXAMPLE $CHAR;
PUT CATX_EXAMPLE $CHAR;
RUN;


DATA CONTEXT;
 INFILE "C:\Users\user\Desktop\SAS\DATA\MyRawData\Pumpkin.dat";
 INPUT NAME $ 16. AGE 3.+1 TYPE $ 1.+1 DATE MMDDYY10. (SCR1 SCR2 SCR3 SCR4 SCR5)(4.1);
 LAST_NAME = SUBSTR(NAME , ANYSPACE(NAME,1)+1);
 LAST_NAME1 = SUBSTR(NAME , LENGTH(NAME),1);
RUN;
PROC PRINT DATA = CONTEXT;
 TITLE "CONTEXT";
RUN;


DATA EX1;
 INPUT PHONE  $ 13.  ;
 SUBSTR(PHONE ,2,3) = "773" ;
 DATALINES ;
 (312)555-1212
;
RUN;

PROC PRINT DATA = EX1;
 TITLE "EX1";
RUN;

DATA EX2 ;
 INFILE "C:\Users\user\Desktop\SAS\Chapter 3_Exercise 2.txt";
 INPUT  FIRST $ 6.+1 LAST $;
 FIRST = CATS(UPCASE(SUBSTR(FIRST,1,1)),LOWCASE(SUBSTR(FIRST,2,5)));
 LAST = CATS(UPCASE(SUBSTR(LAST,1,1)),LOWCASE(SUBSTR(LAST,2)));
RUN;
PROC PRINT DATA = EX2;
 TITLE "EX2";
RUN;

DATA TESTIN;
 INPUT SALE $9.;
 PUT SALE ;
 FMTSALE = INPUT(SALE,COMMA9.);
 PUT FMTSALE;
 DATALINES;
 2,115,353
;
RUN;
