DATA LIBRARY;
 INFILE "C:\Users\user\Desktop\SAS\DATA\MyRawData\Library.dat" TRUNCOVER;
 INPUT NAME $11.+1 BIRTHDATE MMDDYY10.+1 ISSUEDATE ANYDTDTE10. DUEDATE DATE11.;
 DAYSIVERDUE = TODAY() - DUEDATE;
 CURRENTAGE = INT(YRDIF(BIRTHDATE,TODAY(),"AGE"));
 IF ISSUEDATE > "01JAN2012"D THEN NEWCARD = "YES";
RUN;
PROC PRINT DATA = LIBRARY;
 FORMAT ISSUEDATE MMDDYY8. DUEDATE WEEKDATE17.;
 TITLE "SAS";
RUN;


DATA GAME;
 INFILE "C:\Users\user\Desktop\SAS\DATA\MyRawData\Games.dat";
 INPUT MONTH 1 DAY 3-4 TEAM $6-25 HITS 27-28 RUNS 30-31;
 RETAIN MAXRUNS;
 MAXRUNS = MAX(MAXRUNS,RUNS);
 RETAIN RUNTODATE 0;
 RUNTODATE = RUNTODATE + RUNS ;
RUN;
PROC PRINT DATA = GAME;
 TITLE "SAS";
RUN;

DATA TEST_1;
 PUT "BEFORE THE INPUT STATEMENT: " _ALL_;
 INPUT X @@;
 PUT "AFTER THE INPUT STATEMENT: " _ALL_;
 DATALINES;
 1 2 . 3
 ;

DATA TEST_2;
 RETAIN OLD_X ;
 PUT "BEFORE INPUT: " _ALL_;
 INPUT X @@;
 IF X NE . THEN OLD_X = X;
 ELSE X = OLD_X;
 PUT "AFTER ASSIGNMENT: " _ALL_;
 DATALINES;
 1 2 . 3
 ;

DATA SONG;
 INFILE "C:\Users\user\Desktop\SAS\DATA\MyRawData\KBRK.dat";
 INPUT CITY $ 1-15 AGE WJ LST TR FLIP TTR;
 ARRAY SONG(5) WJ LST TR FLIP TTR;
 DO I = 1 TO 5;
 IF SONG(I) = 9 THEN SONG(I) = .;
 END;
RUN;
PROC PRINT DATA = SONG;
 TITLE "SAS";
RUN;

DATA SONG_COUNT ;
 INFILE "C:\Users\user\Desktop\SAS\DATA\MyRawData\KBRK.dat";
 INPUT CITY $ 1-15 AGE WJ LST TR FLIP TTR;
 ARRAY SONG(5) WJ LST TR FLIP TTR;
 RETAIN COUNT 0;
 DO I = 1 TO 5;
 IF SONG(I) = 3 THEN COUNT = COUNT + 1;
 END;
 PUT COUNT;
RUN;

DATA WORK.EARN;
 VALUE = 2000;
 DO YEAR = 1 TO 20;
 INTEREST = VALUE * 0.75;
 VALUE = VALUE+INTEREST;
 OUTPUT;
 END;
RUN;

DATA TEST;
 ARRAY TEST(3) A B C(90,80,70);
 ARRAY SCORE(3) A_S B_S C_S;
 INPUT  SCORE(*);
 DO I = 1 TO 3;
 IF TEST(I) <= SCORE(I) THEN DO NEWSCORE = SCORE(I);
 OUTPUT;
 END;
 END;

 DATALINES ;
 99 60 82
 80 85 75
 ;
RUN;
PROC PRINT DATA = TEST;
 TITLE "TEST";
RUN;
