PROC PRINT DATA = SASHELP.COMPANY;
 WHERE LEVEL5 NOT LIKE "A%" AND LEVEL5 NOT LIKE "S%";
RUN;

PROC PRINT DATA = SASHELP.COMPANY;
 WHERE SCAN(LEVEL5 , -1 ) NOT LIKE "A%" AND SCAN(LEVEL5 , -1 ) NOT LIKE "S%";
RUN;

DATA MARINE;
 INFILE "C:\Users\user\Desktop\SAS\DATA\MyRawData\Lengths.dat";
 INPUT NAME $ FAMILY $ LENGTH @@;
RUN;
PROC SORT DATA=MARINE OUT=SEASORT NODUPKEY;
 BY FAMILY DESCENDING LENGTH;
PROC PRINT DATA = SEASORT;
 TITLE "SORT";
RUN;

PROC SORT DATA=SASHELP.COMPANY OUT=COMPANY1 NODUPKEY;
 BY LEVEL2 DESCENDING LEVEL5;
PROC PRINT DATA = COMPANY1;
 TITLE "COMPANY SORT";
RUN;

DATA ADDRESS ;
 INFILE "C:\Users\user\Desktop\SAS\DATA\MyRawData\Mail.dat";
 INPUT NAME $6. STREET $18. CITY $9. STATE $6.;
RUN;
PROC SORT DATA = ADDRESS OUT = SORTONE
 SORTSEQ = LINGUISTIC(NUMERIC_COLLATION = ON);
 BY STREET;
PROC PRINT DATA = SORTONE;
 TITLE "ADDRESS";
RUN;

DATA CANDY ;
 INFILE "C:\Users\user\Desktop\SAS\DATA\MyRawData\CandySales.dat";
 INPUT NAME $ 1-11 CLASS @15 DATERETURNED MMDDYY10. CANDYTYPE $ QUANTITY ;
 PROFIT = QUANTITY*0.25;
 LABEL DATERETURNED = "DATE RETURNED";
 CANDYTYPE = "TYPE OF CANDY";
RUN;
PROC SORT DATA = CANDY OUT = SALES;
 BY CANDYTYPE DESENDING PROFIT;
PROC PRINT DATA = SALES LABEL;
 BY CANDYTYPE;
 ID CLASS;
 SUM PROFIT;
 VAR NAME DATERETURNED PROFIT;
 FORMAT DATERETURNED DATE9. PROFIT DOLLAR6.2;
 TITLE "CANDY";
RUN;
